# Generated by Django 5.2.1 on 2025-05-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0002_alter_city_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="count",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
