# Generated by Django 5.2.1 on 2025-05-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0003_city_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
